name: all_okr_weekly_notification_for_slack_by_api

on:
  workflow_dispatch:
    inputs:
      year:
        type: choice
        description: year
        required: true
        # 毎年追記すること
        options:
        - 'this_year_at_today'
        - '2023'
        - '2022'
        - '2021'
      quarter_id:
        type: choice
        description: quarter_id
        required: true
        options:
        - 'this_quarter_at_today'
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
      is_more_detail:
        type: choice
        description: is_more_detail
        required: true
        options:
        - '0'
        - '1'
      is_include_full_year:
        type: choice
        description: is_include_full_year
        required: true
        options:
        - '1'
        - '0'
  schedule:
    # 火 0:00 (UTC) -> 火 10:00 (JST)
    - cron: "0 0 * * 2"

jobs:
  okr_weekly_notification_for_slack_by_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run okr_weekly_notification_for_slack_by_api.py
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID_DEFAULT: ${{ secrets.CHANNEL_ID_DEFAULT }}
          CHANNEL_ID_OKR_WEEKLY_NOTIFICATION_FOR_NOTION: ${{ secrets.CHANNEL_ID_OKR_WEEKLY_NOTIFICATION_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          DEFAULT_YEAR: 'this_year_at_today'
          DEFAULT_QUARTER_ID: 'this_quarter_at_today'
          DEFAULT_IS_MORE_DETAIL: '0'
          DEFAULT_IS_INCLUDE_FULL_YEAR: '1'

        # schedule でトリガーされたときはデフォルト値が渡される
        run: python okr_weekly_notification_for_slack_by_api.py ${{ github.event.inputs.year || env.DEFAULT_YEAR }} ${{ github.event.inputs.quarter_id || env.DEFAULT_QUARTER_ID }} ${{ github.event.inputs.is_more_detail || env.DEFAULT_IS_MORE_DETAIL }} ${{ github.event.inputs.is_include_full_year || env.DEFAULT_IS_INCLUDE_FULL_YEAR }}
