name: grouping_okr_weekly_notification_for_slack_by_webhook

on:
  workflow_dispatch:
    inputs:
      year:
        type: choice
        description: year
        required: true
        options:
        - '2022'
        - '2021'
      quarter_id:
        type: choice
        description: quarter_id
        required: true
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
      is_more_detail:
        type: choice
        description: is_more_detail
        required: true
        options:
        - '0'
        - '1'
      user_group:
        type: choice
        description: user_group
        required: true
        options:
        - 'ikeda'
        - 'katakabe'
        - 'seki'
      is_include_full_year:
        type: choice
        description: is_include_full_year
        required: true
        options:
        - '1'
        - '0'

jobs:
  okr_weekly_notification_for_slack_by_webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Group ikeda
        if: ${{ github.event.inputs.user_group == 'ikeda' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID_EEEEG: 2
          USER_ID_SYS: 3
          USER_ID_IKEDA: 4
        run: |
          python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID_EEEEG }} ${{ github.event.inputs.is_include_full_year }}
          python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID_SYS }} ${{ github.event.inputs.is_include_full_year }}
          python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID_IKEDA }} ${{ github.event.inputs.is_include_full_year }}
      - name: Run Group katakabe
        if: ${{ github.event.inputs.user_group == 'katakabe' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID_KATAKABE: 5
          USER_ID_SALES: 6
          USER_ID_HR: 7
        run: |
          python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID_SALES }} ${{ github.event.inputs.is_include_full_year }}
          python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID_HR }} ${{ github.event.inputs.is_include_full_year }}
          python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID_KATAKABE }} ${{ github.event.inputs.is_include_full_year }}
      - name: Run Group seki
        if: ${{ github.event.inputs.user_group == 'seki' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID_SEKI: 11
          USER_ID_DESIGN: 10
        run: |
          python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID_DESIGN }} ${{ github.event.inputs.is_include_full_year }}
          python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID_SEKI }} ${{ github.event.inputs.is_include_full_year }}
