name: individual_okr_weekly_notification_for_slack_by_webhook

on:
  workflow_dispatch:
    inputs:
      year:
        type: choice
        description: year
        required: true
        options:
        - '2022'
        - '2021'
      quarter_id:
        type: choice
        description: quarter_id
        required: true
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
      is_more_detail:
        type: choice
        description: is_more_detail
        required: true
        options:
        - '0'
        - '1'
      user_name:
        type: choice
        description: user_name
        required: true
        options:
        - 'eeeeg'
        - 'sys'
        - 'sales'
        - 'hr'
        - 'design'
        - 'ikeda'
        - 'katakabe'
        - 'seki'
      is_include_full_year:
        type: choice
        description: is_include_full_year
        required: true
        options:
        - '1'
        - '0'

jobs:
  okr_weekly_notification_for_slack_by_webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run For EeeeG (id 2)
        if: ${{ github.event.inputs.user_name == 'eeeeg' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year || '2022' }} ${{ github.event.inputs.quarter_id || '4' }} ${{ github.event.inputs.is_more_detail || '0' }} 2 ${{ github.event.inputs.is_include_full_year || '0' }}
      - name: Run For Sys (id 3)
        if: ${{ github.event.inputs.user_name == 'sys' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year || '2022' }} ${{ github.event.inputs.quarter_id || '4' }} ${{ github.event.inputs.is_more_detail || '0' }} 3 ${{ github.event.inputs.is_include_full_year || '0' }}
      - name: Run For Ikeda (id 4)
        if: ${{ github.event.inputs.user_name == 'ikeda' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year || '2022' }} ${{ github.event.inputs.quarter_id || '4' }} ${{ github.event.inputs.is_more_detail || '0' }} 4 ${{ github.event.inputs.is_include_full_year || '0' }}
      - name: Run For Katakabe (id 5)
        if: ${{ github.event.inputs.user_name == 'katakabe' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year || '2022' }} ${{ github.event.inputs.quarter_id || '4' }} ${{ github.event.inputs.is_more_detail || '0' }} 5 ${{ github.event.inputs.is_include_full_year || '0' }}
      - name: Run For Sales (id 6)
        if: ${{ github.event.inputs.user_name == 'sales' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year || '2022' }} ${{ github.event.inputs.quarter_id || '4' }} ${{ github.event.inputs.is_more_detail || '0' }} 6 ${{ github.event.inputs.is_include_full_year || '0' }}
      - name: Run For HR (id 7)
        if: ${{ github.event.inputs.user_name == 'hr' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year || '2022' }} ${{ github.event.inputs.quarter_id || '4' }} ${{ github.event.inputs.is_more_detail || '0' }} 7 ${{ github.event.inputs.is_include_full_year || '0' }}
      - name: Run For Design (id 10)
        if: ${{ github.event.inputs.user_name == 'design' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year || '2022' }} ${{ github.event.inputs.quarter_id || '4' }} ${{ github.event.inputs.is_more_detail || '0' }} 10 ${{ github.event.inputs.is_include_full_year || '0' }}
      - name: Run For Seki (id 11)
        if: ${{ github.event.inputs.user_name == 'seki' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year || '2022' }} ${{ github.event.inputs.quarter_id || '4' }} ${{ github.event.inputs.is_more_detail || '0' }} 11 ${{ github.event.inputs.is_include_full_year || '0' }}
