name: individual_okr_weekly_notification_for_slack_by_webhook

on:
  workflow_dispatch:
    inputs:
      year:
        type: choice
        description: year
        required: true
        options:
        - '2023'
        - '2022'
        - '2021'
      quarter_id:
        type: choice
        description: quarter_id
        required: true
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
      is_more_detail:
        type: choice
        description: is_more_detail
        required: true
        options:
        - '0'
        - '1'
      user_name:
        type: choice
        description: user_name
        required: true
        options:
        - 'eeeeg'
        - 'sys'
        - 'sales'
        - 'hr'
        - 'design'
        - 'ikeda'
        - 'katakabe'
        - 'seki'
        - 'inoue'
      is_include_full_year:
        type: choice
        description: is_include_full_year
        required: true
        options:
        - '1'
        - '0'

jobs:
  okr_weekly_notification_for_slack_by_webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run For EeeeG
        if: ${{ github.event.inputs.user_name == 'eeeeg' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID: 2
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID }} ${{ github.event.inputs.is_include_full_year }}
      - name: Run For Sys
        if: ${{ github.event.inputs.user_name == 'sys' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID: 3
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID }} ${{ github.event.inputs.is_include_full_year }}
      - name: Run For Ikeda
        if: ${{ github.event.inputs.user_name == 'ikeda' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID: 4
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID }} ${{ github.event.inputs.is_include_full_year }}
      - name: Run For Katakabe
        if: ${{ github.event.inputs.user_name == 'katakabe' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID: 5
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID }} ${{ github.event.inputs.is_include_full_year }}
      - name: Run For Sales
        if: ${{ github.event.inputs.user_name == 'sales' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID: 6
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID }} ${{ github.event.inputs.is_include_full_year }}
      - name: Run For HR
        if: ${{ github.event.inputs.user_name == 'hr' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID: 7
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID }} ${{ github.event.inputs.is_include_full_year }}
      - name: Run For Design
        if: ${{ github.event.inputs.user_name == 'design' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID: 10
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID }} ${{ github.event.inputs.is_include_full_year }}
      - name: Run For Seki
        if: ${{ github.event.inputs.user_name == 'seki' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID: 11
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID }} ${{ github.event.inputs.is_include_full_year }}
      - name: Run For Inoue
        if: ${{ github.event.inputs.user_name == 'inoue' }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
          USER_ID: 12
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year }} ${{ github.event.inputs.quarter_id }} ${{ github.event.inputs.is_more_detail }} ${{ env.USER_ID }} ${{ github.event.inputs.is_include_full_year }}
