name: okr_weekly_notification_for_slack_by_webhook

on:
  workflow_dispatch:
    inputs:
      year:
        type: choice
        description: year
        required: true
        options:
        - '2022'
        - '2021'
      quarter_id:
        type: choice
        description: quarter_id
        required: true
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
      is_more_detail:
        type: choice
        description: is_more_detail
        required: true
        options:
        - '0'
        - '1'
      user_id:
        type: choice
        description: user_id
        required: false
        options:
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        - '7'
        - '8'
        - '9'
        - '10'
        - '11'

jobs:
  okr_weekly_notification_for_slack_by_webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run okr_weekly_notification_for_slack_by_webhook.py
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_FOR_NOTION: ${{ secrets.WEBHOOK_URL_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python okr_weekly_notification_for_slack_by_webhook.py ${{ github.event.inputs.year || '2022' }} ${{ github.event.inputs.quarter_id || '4' }} ${{ github.event.inputs.is_more_detail || '0' }} ${{ github.event.inputs.user_id }}
